import React, { createContext, useContext, useState, useEffect, ReactNode } from 'react';

export type Language =
  | 'en' | 'te' | 'hi' | 'ta' | 'kn' | 'ml' | 'mr' | 'bn' | 'gu' | 'pa';

interface Translations {
  [key: string]: {
    [key in Language]: string;
  };
}

export const translations: Translations = {
  // Language Selection
  selectLanguage: {
    en: "Choose Your Language",
    te: "మీ భాషను ఎంచుకోండి",
    hi: "अपनी भाषा चुनें",
    ta: "உங்கள் மொழியைத் தேர்ந்தெடுக்கவும்",
    kn: "ನಿಮ್ಮ ಭಾಷೆಯನ್ನು ಆಯ್ಕೆಮಾಡಿ",
    ml: "നിങ്ങളുടെ ഭാഷ തിരഞ്ഞെടുക്കുക",
    mr: "तुमची भाषा निवडा",
    bn: "আপনার ভাষা নির্বাচন করুন",
    gu: "તમારી ભાષા પસંદ કરો",
    pa: "ਆਪਣੀ ਭਾਸ਼ਾ ਚੁਣੋ",
  },
  welcome: {
    en: "Welcome to SheRise",
    te: "SheRise కు స్వాగతం",
    hi: "SheRise में आपका स्वागत है",
    ta: "SheRise-க்கு வரவேற்கிறோம்",
    kn: "SheRise ಗೆ ಸ್ವಾಗತ",
    ml: "SheRise-ലേക്ക് സ്വാഗതം",
    mr: "SheRise मध्ये आपले स्वागत आहे",
    bn: "SheRise-এ স্বাগতম",
    gu: "SheRise માં આપનું સ્વાગત છે",
    pa: "SheRise ਵਿੱਚ ਤੁਹਾਡਾ ਸਵਾਗਤ ਹੈ",
  },
  tagline: {
    en: "of the women, for the women, by the women",
    te: "స్త్రీల యొక్క, స్త్రీల కోసం, స్త్రీల ద్వారా",
    hi: "महिलाओं का, महिलाओं के लिए, महिलाओं द्वारा",
    ta: "பெண்களின், பெண்களுக்காக, பெண்களால்",
    kn: "ಮಹಿಳೆಯರ, ಮಹಿಳೆಯರಿಗಾಗಿ, ಮಹಿಳೆಯರಿಂದ",
    ml: "സ്ത്രീകളുടെ, സ്ത്രീകൾക്കായി, സ്ത്രീകൾ",
    mr: "महिलांचे, महिलांसाठी, महिलांकडून",
    bn: "নারীদের, নারীদের জন্য, নারীদের দ্বারা",
    gu: "સ્ત્રીઓનું, સ્ત્રીઓ માટે, સ્ત્રીઓ દ્વારા",
    pa: "ਔਰਤਾਂ ਦਾ, ਔਰਤਾਂ ਲਈ, ਔਰਤਾਂ ਦੁਆਰਾ",
  },
  login: {
    en: "Login",
    te: "లాగిన్",
    hi: "लॉगिन",
    ta: "உள்நுழைய",
    kn: "ಲಾಗಿನ್",
    ml: "ലോഗിൻ",
    mr: "लॉगिन",
    bn: "লগইন",
    gu: "લોગિન",
    pa: "ਲੌਗਇਨ",
  },
  register: {
    en: "Register",
    te: "నమోదు",
    hi: "पंजीकरण",
    ta: "பதிவு செய்",
    kn: "ನೋಂದಣಿ",
    ml: "രജിസ്റ്റർ",
    mr: "नोंदणी",
    bn: "নিবন্ধন",
    gu: "નોંધણી",
    pa: "ਰਜਿਸਟਰ",
  },
  email: {
    en: "Email Address",
    te: "ఇమెయిల్ చిరునామా",
    hi: "ईमेल पता",
    ta: "மின்னஞ்சல் முகவரி",
    kn: "ಇಮೇಲ್ ವಿಳಾಸ",
    ml: "ഇമെയിൽ വിലാസം",
    mr: "ईमेल पत्ता",
    bn: "ইমেইল ঠিকানা",
    gu: "ઇમેઇલ સરનામું",
    pa: "ਈਮੇਲ ਪਤਾ",
  },
  phone: {
    en: "Phone Number",
    te: "ఫోన్ నంబర్",
    hi: "फ़ोन नंबर",
    ta: "தொலைபேசி எண்",
    kn: "ಫೋನ್ ಸಂಖ್ಯೆ",
    ml: "ഫോൺ നമ്പർ",
    mr: "फोन नंबर",
    bn: "ফোন নম্বর",
    gu: "ફોન નંબર",
    pa: "ਫ਼ੋਨ ਨੰਬਰ",
  },
  password: {
    en: "Password",
    te: "పాస్వర్డ్",
    hi: "पासवर्ड",
    ta: "கடவுச்சொல்",
    kn: "ಪಾಸ್‌ವರ್ಡ್",
    ml: "പാസ്‌വേഡ്",
    mr: "पासवर्ड",
    bn: "পাসওয়ার্ড",
    gu: "પાસવર્ડ",
    pa: "ਪਾਸਵਰਡ",
  },
  sendOtp: {
    en: "Send OTP",
    te: "OTP పంపు",
    hi: "OTP भेजें",
    ta: "OTP அனுப்பு",
    kn: "OTP ಕಳುಹಿಸಿ",
    ml: "OTP അയയ്ക്കുക",
    mr: "OTP पाठवा",
    bn: "OTP পাঠান",
    gu: "OTP મોકલો",
    pa: "OTP ਭੇਜੋ",
  },
  enterOtp: {
    en: "Enter OTP",
    te: "OTP నమోదు చేయండి",
    hi: "OTP दर्ज करें",
    ta: "OTP உள்ளிடவும்",
    kn: "OTP ನಮೂದಿಸಿ",
    ml: "OTP നൽകുക",
    mr: "OTP प्रविष्ट करा",
    bn: "OTP লিখুন",
    gu: "OTP દાખલ કરો",
    pa: "OTP ਦਾਖਲ ਕਰੋ",
  },
  noAccount: {
    en: "Don't have an account?",
    te: "ఖాతా లేదా?",
    hi: "खाता नहीं है?",
    ta: "கணக்கு இல்லையா?",
    kn: "ಖಾತೆ ಇಲ್ಲವೇ?",
    ml: "അക്കൗണ്ട് ഇല്ലേ?",
    mr: "खाते नाही?",
    bn: "অ্যাকাউন্ট নেই?",
    gu: "ખાતું નથી?",
    pa: "ਖਾਤਾ ਨਹੀਂ?",
  },
  haveAccount: {
    en: "Already have an account?",
    te: "ఇప్పటికే ఖాతా ఉందా?",
    hi: "पहले से खाता है?",
    ta: "ஏற்கனவே கணக்கு உள்ளதா?",
    kn: "ಈಗಾಗಲೇ ಖಾತೆ ಇದೆಯೇ?",
    ml: "ഇതിനകം അക്കൗണ്ട് ഉണ്ടോ?",
    mr: "आधीच खाते आहे?",
    bn: "ইতিমধ্যে অ্যাকাউন্ট আছে?",
    gu: "પહેલેથી ખાતું છે?",
    pa: "ਪਹਿਲਾਂ ਤੋਂ ਖਾਤਾ ਹੈ?",
  },
  fullName: {
    en: "Full Name",
    te: "పూర్తి పేరు",
    hi: "पूरा नाम",
    ta: "முழு பெயர்",
    kn: "ಪೂರ್ಣ ಹೆಸರು",
    ml: "പൂർണ്ണ നാമം",
    mr: "पूर्ण नाव",
    bn: "পুরো নাম",
    gu: "પૂરું નામ",
    pa: "ਪੂਰਾ ਨਾਮ",
  },
  address: {
    en: "Address",
    te: "చిరునామా",
    hi: "पता",
    ta: "முகவரி",
    kn: "ವಿಳಾಸ",
    ml: "വിലാസം",
    mr: "पत्ता",
    bn: "ঠিকানা",
    gu: "સરનામું",
    pa: "ਪਤਾ",
  },
  aadhaar: {
    en: "Aadhaar Number (Last 4 digits)",
    te: "ఆధార్ నంబర్ (చివరి 4 అంకెలు)",
    hi: "आधार नंबर (अंतिम 4 अंक)",
    ta: "ஆதார் எண் (கடைசி 4 இலக்கங்கள்)",
    kn: "ಆಧಾರ್ ಸಂಖ್ಯೆ (ಕೊನೆಯ 4 ಅಂಕೆಗಳು)",
    ml: "ആധാർ നമ്പർ (അവസാന 4 അക്കങ്ങൾ)",
    mr: "आधार क्रमांक (शेवटचे 4 अंक)",
    bn: "আধার নম্বর (শেষ 4 সংখ্যা)",
    gu: "આધાર નંબર (છેલ્લા 4 અંક)",
    pa: "ਆਧਾਰ ਨੰਬਰ (ਆਖਰੀ 4 ਅੰਕ)",
  },
  verifyAadhaar: {
    en: "Verify with Aadhaar OTP",
    te: "ఆధార్ OTP తో ధృవీకరించండి",
    hi: "आधार OTP से सत्यापित करें",
    ta: "ஆதார் OTP மூலம் சரிபார்க்கவும்",
    kn: "ಆಧಾರ್ OTP ಮೂಲಕ ಪರಿಶೀಲಿಸಿ",
    ml: "ആധാർ OTP ഉപയോഗിച്ച് പരിശോധിക്കുക",
    mr: "आधार OTP ने सत्यापित करा",
    bn: "আধার OTP দিয়ে যাচাই করুন",
    gu: "આધાર OTP થી ચકાસો",
    pa: "ਆਧਾਰ OTP ਨਾਲ ਪੁਸ਼ਟੀ ਕਰੋ",
  },
  giveWork: {
    en: "Give Work",
    te: "పని ఇవ్వండి",
    hi: "काम दें",
    ta: "வேலை கொடு",
    kn: "ಕೆಲಸ ಕೊಡಿ",
    ml: "ജോലി നൽകുക",
    mr: "काम द्या",
    bn: "কাজ দিন",
    gu: "કામ આપો",
    pa: "ਕੰਮ ਦਿਓ",
  },
  takeWork: {
    en: "Take Work",
    te: "పని తీసుకోండి",
    hi: "काम लें",
    ta: "வேலை எடு",
    kn: "ಕೆಲಸ ತೆಗೆದುಕೊಳ್ಳಿ",
    ml: "ജോലി എടുക്കുക",
    mr: "काम घ्या",
    bn: "কাজ নিন",
    gu: "કામ લો",
    pa: "ਕੰਮ ਲਵੋ",
  },
  dashboard: {
    en: "Dashboard",
    te: "డ్యాష్‌బోర్డ్",
    hi: "डैशबोर्ड",
    ta: "டாஷ்போர்டு",
    kn: "ಡ್ಯಾಶ್‌ಬೋರ್ಡ್",
    ml: "ഡാഷ്ബോർഡ്",
    mr: "डॅशबोर्ड",
    bn: "ড্যাশবোর্ড",
    gu: "ડેશબોર્ડ",
    pa: "ਡੈਸ਼ਬੋਰਡ",
  },
  profile: {
    en: "Profile",
    te: "ప్రొఫైల్",
    hi: "प्रोफाइल",
    ta: "சுயவிவரம்",
    kn: "ಪ್ರೊಫೈಲ್",
    ml: "പ്രൊഫൈൽ",
    mr: "प्रोफाइल",
    bn: "প্রোফাইল",
    gu: "પ્રોફાઇલ",
    pa: "ਪ੍ਰੋਫਾਈਲ",
  },
  skills: {
    en: "My Skills",
    te: "నా నైపుణ్యాలు",
    hi: "मेरे कौशल",
    ta: "என் திறன்கள்",
    kn: "ನನ್ನ ಕೌಶಲ್ಯಗಳು",
    ml: "എന്റെ കഴിവുകൾ",
    mr: "माझी कौशल्ये",
    bn: "আমার দক্ষতা",
    gu: "મારી કુશળતાઓ",
    pa: "ਮੇਰੇ ਹੁਨਰ",
  },
  settings: {
    en: "Settings",
    te: "సెట్టింగ్‌లు",
    hi: "सेटिंग्स",
    ta: "அமைப்புகள்",
    kn: "ಸೆಟ್ಟಿಂಗ್‌ಗಳು",
    ml: "ക്രമീകരണങ്ങൾ",
    mr: "सेटिंग्ज",
    bn: "সেটিংস",
    gu: "સેટિંગ્સ",
    pa: "ਸੈਟਿੰਗਾਂ",
  },
  logout: {
    en: "Logout",
    te: "లాగ్అవుట్",
    hi: "लॉगआउट",
    ta: "வெளியேறு",
    kn: "ಲಾಗ್ಔಟ್",
    ml: "ലോഗ്ഔട്ട്",
    mr: "लॉगआउट",
    bn: "লগআউট",
    gu: "લોગઆઉટ",
    pa: "ਲੌਗਆਉਟ",
  },
  credits: {
    en: "Credits",
    te: "క్రెడిట్స్",
    hi: "क्रेडिट्स",
    ta: "கிரெடிட்ஸ்",
    kn: "ಕ್ರೆಡಿಟ್ಸ್",
    ml: "ക്രെഡിറ്റ്സ്",
    mr: "क्रेडिट्स",
    bn: "ক্রেডিটস",
    gu: "ક્રેડિટ્સ",
    pa: "ਕ੍ਰੈਡਿਟਸ",
  },
  reviews: {
    en: "Reviews",
    te: "సమీక్షలు",
    hi: "समीक्षाएं",
    ta: "மதிப்புரைகள்",
    kn: "ವಿಮರ್ಶೆಗಳು",
    ml: "അവലോകനങ്ങൾ",
    mr: "पुनरावलोकने",
    bn: "পর্যালোচনা",
    gu: "સમીક્ષાઓ",
    pa: "ਸਮੀਖਿਆਵਾਂ",
  },
  history: {
    en: "Work History",
    te: "పని చరిత్ర",
    hi: "कार्य इतिहास",
    ta: "வேலை வரலாறு",
    kn: "ಕೆಲಸದ ಇತಿಹಾಸ",
    ml: "ജോലി ചരിത്രം",
    mr: "कामाचा इतिहास",
    bn: "কাজের ইতিহাস",
    gu: "કામનો ઇતિહાસ",
    pa: "ਕੰਮ ਦਾ ਇਤਿਹਾਸ",
  },
  location: {
    en: "Location",
    te: "స్థానం",
    hi: "स्थान",
    ta: "இடம்",
    kn: "ಸ್ಥಳ",
    ml: "സ്ഥലം",
    mr: "स्थान",
    bn: "অবস্থান",
    gu: "સ્થાન",
    pa: "ਸਥਾਨ",
  },
  termsConditions: {
    en: "Terms & Conditions",
    te: "నిబంధనలు మరియు షరతులు",
    hi: "नियम और शर्तें",
    ta: "விதிமுறைகள் & நிபந்தனைகள்",
    kn: "ನಿಯಮಗಳು & ಷರತ್ತುಗಳು",
    ml: "നിബന്ധനകളും വ്യവസ്ഥകളും",
    mr: "अटी व शर्ती",
    bn: "শর্তাবলী",
    gu: "નિયમો અને શરતો",
    pa: "ਨਿਯਮ ਅਤੇ ਸ਼ਰਤਾਂ",
  },
  womenOnly: {
    en: "This platform is exclusively for women",
    te: "ఈ ప్లాట్‌ఫాం ప్రత్యేకంగా మహిళల కోసం",
    hi: "यह प्लेटफ़ॉर्म विशेष रूप से महिलाओं के लिए है",
    ta: "இந்த தளம் பெண்களுக்கு மட்டுமே",
    kn: "ಈ ವೇದಿಕೆ ಮಹಿಳೆಯರಿಗೆ ಮಾತ್ರ",
    ml: "ഈ പ്ലാറ്റ്‌ഫോം സ്ത്രീകൾക്ക് മാത്രം",
    mr: "हे व्यासपीठ फक्त महिलांसाठी आहे",
    bn: "এই প্ল্যাটফর্ম শুধুমাত্র মহিলাদের জন্য",
    gu: "આ પ્લેટફોર્મ ફક્ત મહિલાઓ માટે છે",
    pa: "ਇਹ ਪਲੇਟਫਾਰਮ ਸਿਰਫ਼ ਔਰਤਾਂ ਲਈ ਹੈ",
  },
  continueBtn: {
    en: "Continue",
    te: "కొనసాగించు",
    hi: "जारी रखें",
    ta: "தொடரவும்",
    kn: "ಮುಂದುವರಿಸಿ",
    ml: "തുടരുക",
    mr: "सुरू ठेवा",
    bn: "চালিয়ে যান",
    gu: "ચાલુ રાખો",
    pa: "ਜਾਰੀ ਰੱਖੋ",
  },
  submit: {
    en: "Submit",
    te: "సమర్పించు",
    hi: "सबमिट करें",
    ta: "சமர்ப்பிக்க",
    kn: "ಸಲ್ಲಿಸು",
    ml: "സമർപ്പിക്കുക",
    mr: "सबमिट करा",
    bn: "জমা দিন",
    gu: "સબમિટ કરો",
    pa: "ਜਮ੍ਹਾਂ ਕਰੋ",
  },
  callWorker: {
    en: "Call Worker",
    te: "కార్మికుడిని కాల్ చేయండి",
    hi: "कर्मचारी को कॉल करें",
    ta: "தொழிலாளியை அழைக்கவும்",
    kn: "ಕೆಲಸಗಾರನನ್ನು ಕರೆ ಮಾಡಿ",
    ml: "തൊഴിലാളിയെ വിളിക്കുക",
    mr: "कामगाराला कॉल करा",
    bn: "কর্মীকে কল করুন",
    gu: "કામદારને કૉલ કરો",
    pa: "ਕਾਮੇ ਨੂੰ ਕਾਲ ਕਰੋ",
  },
  videoCall: {
    en: "Video Call",
    te: "వీడియో కాల్",
    hi: "वीडियो कॉल",
    ta: "வீடியோ அழைப்பு",
    kn: "ವೀಡಿಯೊ ಕಾಲ್",
    ml: "വീഡിയോ കോൾ",
    mr: "व्हिडिओ कॉल",
    bn: "ভিডিও কল",
    gu: "વિડિઓ કૉલ",
    pa: "ਵੀਡੀਓ ਕਾਲ",
  },
  nearMe: {
    en: "Near Me",
    te: "నాకు సమీపంలో",
    hi: "मेरे पास",
    ta: "என் அருகில்",
    kn: "ನನ್ನ ಹತ್ತಿರ",
    ml: "എന്റെ അടുത്ത്",
    mr: "माझ्या जवळ",
    bn: "আমার কাছে",
    gu: "મારી નજીક",
    pa: "ਮੇਰੇ ਨੇੜੇ",
  },
  radius: {
    en: "Radius",
    te: "వ్యాసార్థం",
    hi: "त्रिज्या",
    ta: "ஆரம்",
    kn: "ತ್ರಿಜ್ಯ",
    ml: "ആരം",
    mr: "त्रिज्या",
    bn: "ব্যাসার্ধ",
    gu: "ત્રિજ્યા",
    pa: "ਘੇਰਾ",
  },
};

export const languages = [
  { code: 'en' as Language, name: 'English', native: 'English' },
  { code: 'te' as Language, name: 'Telugu', native: 'తెలుగు' },
  { code: 'hi' as Language, name: 'Hindi', native: 'हिन्दी' },
  { code: 'ta' as Language, name: 'Tamil', native: 'தமிழ்' },
  { code: 'kn' as Language, name: 'Kannada', native: 'ಕನ್ನಡ' },
  { code: 'ml' as Language, name: 'Malayalam', native: 'മലയാളം' },
  { code: 'mr' as Language, name: 'Marathi', native: 'मराठी' },
  { code: 'bn' as Language, name: 'Bengali', native: 'বাংলা' },
  { code: 'gu' as Language, name: 'Gujarati', native: 'ગુજરાતી' },
  { code: 'pa' as Language, name: 'Punjabi', native: 'ਪੰਜਾਬੀ' },
];

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem('feminine-shakthi-language');
    return (saved as Language) || 'en';
  });

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('feminine-shakthi-language', lang);
  };

  const t = (key: string): string => {
    return translations[key]?.[language] || translations[key]?.['en'] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
